"use client";

import { createContext, useContext } from "react";

export type Lang = "ru" | "en";

const translations = {
  // Header
  "app.title": { ru: "Tusovka", en: "Tusovka" },
  "app.subtitle": { ru: "Организатор мероприятий", en: "Event Organizer" },

  // Tabs
  "tab.events": { ru: "Тусовки", en: "Events" },
  "tab.users": { ru: "Пользователи", en: "Users" },
  "tab.statistics": { ru: "Статистика", en: "Statistics" },
  "tab.admin": { ru: "Админка", en: "Admin" },
  "tab.survey": { ru: "Опросник", en: "Survey" },

  // Auth
  "auth.login": { ru: "Вход", en: "Login" },
  "auth.register": { ru: "Регистрация", en: "Register" },
  "auth.pin": { ru: "PIN-код", en: "PIN code" },
  "auth.nickname": { ru: "Никнейм", en: "Nickname" },
  "auth.enter": { ru: "Войти", en: "Login" },
  "auth.registerBtn": { ru: "Зарегистрироваться", en: "Register" },
  "auth.noAccount": { ru: "Нет аккаунта? Зарегистрироваться", en: "No account? Register" },
  "auth.hasAccount": { ru: "Уже есть аккаунт? Войти", en: "Already have an account? Login" },
  "auth.wrongPin": { ru: "Неверный PIN-код", en: "Wrong PIN code" },
  "auth.min2chars": { ru: "Минимум 2 символа", en: "Minimum 2 characters" },
  "auth.registerError": { ru: "Ошибка регистрации", en: "Registration error" },
  "auth.rememberPin": { ru: "Запомните ваш PIN-код!", en: "Remember your PIN code!" },
  "auth.pinShownOnce": { ru: "Этот PIN-код нужен для входа. Сохраните его — он показывается только один раз.", en: "This PIN code is needed to log in. Save it — it is shown only once." },
  "auth.remembered": { ru: "Я запомнил, продолжить", en: "I remembered, continue" },
  "auth.pinAutoGenerated": { ru: "PIN-код сгенерируется автоматически.", en: "PIN code will be generated automatically." },
  "auth.chooseNickname": { ru: "Выберите никнейм, по которому друзья смогут вас узнать.", en: "Choose a nickname so your friends can recognize you." },

  // Events
  "event.new": { ru: "Новый ивент", en: "New event" },
  "event.createFirst": { ru: "Создать первый ивент", en: "Create first event" },
  "event.noEvents": { ru: "Пока нет ни одного ивента", en: "No events yet" },
  "event.create": { ru: "Создать", en: "Create" },
  "event.delete": { ru: "Удалить", en: "Delete" },
  "event.title": { ru: "Название", en: "Title" },
  "event.description": { ru: "Описание (необязательно)", en: "Description (optional)" },
  "event.newEvent": { ru: "Новый ивент", en: "New event" },
  "event.createError": { ru: "Ошибка создания ивента", en: "Error creating event" },
  "event.deleteConfirm": { ru: "Введите ваш PIN-код для подтверждения удаления", en: "Enter your PIN code to confirm deletion" },
  "event.participants": { ru: "участн.", en: "members" },
  "event.addDescription": { ru: "Добавить описание", en: "Add description" },

  // Users
  "users.all": { ru: "Все пользователи", en: "All users" },
  "users.noUsers": { ru: "Пока никто не зарегистрировался", en: "No users registered yet" },
  "users.changeNickname": { ru: "Изменить никнейм", en: "Change nickname" },
  "users.changePin": { ru: "Сменить PIN", en: "Change PIN" },
  "users.deleteUser": { ru: "Удалить", en: "Delete" },
  "users.deleteConfirm": { ru: "Удалить этого пользователя? Все его данные будут потеряны.", en: "Delete this user? All their data will be lost." },
  "users.newPin": { ru: "Новый PIN (4 цифры)", en: "New PIN (4 digits)" },

  // Admin
  "admin.title": { ru: "Админка", en: "Admin" },
  "admin.addBlock": { ru: "Добавить блок", en: "Add block" },
  "admin.addBlockTitle": { ru: "Добавить блок", en: "Add block" },
  "admin.noBlocks": { ru: "Добавьте блоки для настройки ивента", en: "Add blocks to set up the event" },
  "admin.add": { ru: "Добавить", en: "Add" },
  "admin.delete": { ru: "Удалить", en: "Delete" },
  "admin.save": { ru: "Сохранить", en: "Save" },
  "admin.cancel": { ru: "Отмена", en: "Cancel" },
  "admin.edit": { ru: "Изм.", en: "Edit" },
  "admin.del": { ru: "Уд.", en: "Del" },
  "admin.noItems": { ru: "Нет элементов. Нажмите \"Добавить\" чтобы начать.", en: "No items. Click \"Add\" to start." },
  "admin.import": { ru: "Импорт", en: "Import" },
  "admin.export": { ru: "Экспорт", en: "Export" },
  "admin.importTitle": { ru: "Импорт позиций", en: "Import items" },
  "admin.importHint": { ru: "Введите позиции, каждая с новой строки в формате:", en: "Enter items, one per line in format:" },
  "admin.importBtn": { ru: "Импортировать", en: "Import" },
  "admin.copied": { ru: "Скопировано!", en: "Copied!" },
  "admin.bringOwn": { ru: "Взять своё", en: "Bring your own" },
  "admin.buy": { ru: "Купить", en: "Buy" },
  "admin.car": { ru: "Машина", en: "Car" },
  "admin.other": { ru: "Другое", en: "Other" },
  "admin.forEveryone": { ru: "Для всех участников", en: "For all participants" },
  "admin.sharedFuel": { ru: "Средняя цена бензина для всех участников", en: "Average fuel price for all participants" },
  "admin.driverPays": { ru: "Водитель платит за бензин", en: "Driver pays for fuel" },
  "admin.itemType": { ru: "Тип позиции:", en: "Item type:" },
  "admin.transportType": { ru: "Тип транспорта:", en: "Transport type:" },
  "admin.someoneHas": { ru: "У кого-то есть эта вещь", en: "Someone has this item" },
  "admin.buyInStore": { ru: "Нужно купить в магазине", en: "Need to buy in store" },
  "admin.carWithSeats": { ru: "Автомобиль с местами", en: "Car with seats" },
  "admin.busTrainEtc": { ru: "Автобус, поезд и т.д.", en: "Bus, train, etc." },

  // Form placeholders
  "form.name": { ru: "Название", en: "Name" },
  "form.quantity": { ru: "Количество", en: "Quantity" },
  "form.whereToBuy": { ru: "Где купить", en: "Where to buy" },
  "form.price": { ru: "Цена", en: "Price" },
  "form.whoBought": { ru: "Кто купил?", en: "Who bought?" },
  "form.totalSeats": { ru: "Всего мест", en: "Total seats" },
  "form.departureDate": { ru: "День выезда", en: "Departure date" },
  "form.fuelCost": { ru: "Сумма за бензин", en: "Fuel cost" },
  "form.whoPaidFuel": { ru: "Кто заплатил за бензин?", en: "Who paid for fuel?" },
  "form.vacantSpots": { ru: "Вакантных мест", en: "Vacant spots" },
  "form.notes": { ru: "Примечания", en: "Notes" },

  // Date & Place
  "datePlace.startDate": { ru: "Дата начала", en: "Start date" },
  "datePlace.startTime": { ru: "Время начала", en: "Start time" },
  "datePlace.endDate": { ru: "Дата окончания", en: "End date" },
  "datePlace.endTime": { ru: "Время окончания", en: "End time" },
  "datePlace.place": { ru: "Место проведения", en: "Venue" },

  // Survey
  "survey.title": { ru: "Опросник", en: "Survey" },
  "survey.attendance": { ru: "Участие", en: "Attendance" },
  "survey.areYouGoing": { ru: "Вы идёте?", en: "Are you going?" },
  "survey.yes": { ru: "Да", en: "Yes" },
  "survey.no": { ru: "Нет", en: "No" },
  "survey.notSure": { ru: "Не уверен", en: "Not sure" },
  "survey.arrivalDate": { ru: "Дата приезда", en: "Arrival date" },
  "survey.departureDate": { ru: "Дата отъезда", en: "Departure date" },
  "survey.datesNotSet": { ru: "Даты мероприятия ещё не указаны в админке (блок \"Дата и место\")", en: "Event dates not set in admin (\"Date & Place\" block)" },
  "survey.save": { ru: "Сохранить ответы", en: "Save answers" },
  "survey.saving": { ru: "Сохранение...", en: "Saving..." },
  "survey.loginRequired": { ru: "Войдите для прохождения опросника", en: "Login to fill the survey" },
  "survey.whatDrink": { ru: "Что вы пьёте?", en: "What do you drink?" },
  "survey.all": { ru: "Всё", en: "Everything" },
  "survey.dontDrink": { ru: "Не пью", en: "Don't drink" },
  "survey.drinkOnly": { ru: "Пью только...", en: "I only drink..." },
  "survey.selectDrinks": { ru: "Выберите что вы пьёте:", en: "Select what you drink:" },
  "survey.howTravel": { ru: "Как вы добираетесь?", en: "How are you getting there?" },
  "survey.passenger": { ru: "Пассажиром", en: "As passenger" },
  "survey.selfTravel": { ru: "Своим ходом", en: "On my own" },
  "survey.noCars": { ru: "(нет машин)", en: "(no cars)" },
  "survey.availableCars": { ru: "Доступные машины:", en: "Available cars:" },
  "survey.otherTransport": { ru: "Другие варианты транспорта:", en: "Other transport options:" },
  "survey.freeSpots": { ru: "свободных мест", en: "free spots" },
  "survey.noSpots": { ru: "Мест нет", en: "No spots" },
  "survey.sit": { ru: "Сесть", en: "Join" },
  "survey.cancelSeat": { ru: "Отменить", en: "Cancel" },
  "survey.chooseTent": { ru: "Выберите палатку", en: "Choose a tent" },
  "survey.take": { ru: "Занять", en: "Take" },
  "survey.markBring": { ru: "Отметьте что вы можете взять с собой", en: "Mark what you can bring" },
  "survey.bring": { ru: "Беру", en: "I'll bring" },
  "survey.dontBring": { ru: "Не беру", en: "Not bringing" },
  "survey.joinFunding": { ru: "Хотите участвовать в складчине?", en: "Want to chip in?" },
  "survey.joinBtn": { ru: "Участвую", en: "I'm in" },
  "survey.leaveBtn": { ru: "Отказаться", en: "Opt out" },
  "survey.notJoinBtn": { ru: "Не участвую", en: "Not joining" },
  "survey.plannedActivities": { ru: "Запланированные мероприятия", en: "Planned activities" },

  // Statistics
  "stats.participants": { ru: "Участники", en: "Participants" },
  "stats.finances": { ru: "Финансы", en: "Finances" },
  "stats.totalSpent": { ru: "Общие затраты", en: "Total spent" },
  "stats.purchases": { ru: "Покупки", en: "Purchases" },
  "stats.debt": { ru: "Должок", en: "Debt" },
  "stats.alcohol": { ru: "Алкоголь", en: "Alcohol" },
  "stats.pyroFilm": { ru: "Пиро/Плёнка", en: "Pyro/Film" },
  "stats.fuel": { ru: "Бензин", en: "Fuel" },
  "stats.total": { ru: "Итого", en: "Total" },
  "stats.owesTo": { ru: "Кому торчишь?", en: "Who do you owe?" },
  "stats.owedBack": { ru: "Ему должны вернуть", en: "Owed back" },
  "stats.owesLabel": { ru: "Кому торчишь:", en: "Owes to:" },
  "stats.notGoing": { ru: "не идёт", en: "not going" },
  "stats.noItems": { ru: "Нет элементов", en: "No items" },
  "stats.nobodyBrings": { ru: "Никто не берёт!", en: "Nobody brings!" },
  "stats.refresh": { ru: "Обновить данные", en: "Refresh data" },
  "stats.dateAndPlace": { ru: "Дата и место", en: "Date & Place" },
  "stats.brings": { ru: "берёт", en: "brings" },
  "stats.booked": { ru: "бронь", en: "booked" },
  "stats.rides": { ru: "едет", en: "rides" },
  "stats.participates": { ru: "участвует", en: "participates" },
  "stats.oweHim": { ru: "Ему должны", en: "Owed to them" },

  // Block types
  "block.datePlace": { ru: "Дата и место", en: "Date & Place" },
  "block.food": { ru: "Еда", en: "Food" },
  "block.alcohol": { ru: "Алкоголь", en: "Alcohol" },
  "block.tent": { ru: "Палатки", en: "Tents" },
  "block.equipment": { ru: "Оснастка", en: "Equipment" },
  "block.transport": { ru: "Транспорт", en: "Transport" },
  "block.pyrotechnics": { ru: "Пиротехника", en: "Pyrotechnics" },
  "block.film": { ru: "Фотоплёнка", en: "Film" },
  "block.dayFood": { ru: "Паёк", en: "Day rations" },
  "block.activities": { ru: "Мероприятия", en: "Activities" },
  "block.custom": { ru: "Пользовательский", en: "Custom" },

  // Common
  "common.back": { ru: "← Назад", en: "← Back" },
  "common.price": { ru: "Цена", en: "Price" },
  "common.forAll": { ru: "Для всех", en: "For all" },
  "common.departure": { ru: "Выезд", en: "Departure" },
  "common.fuelLabel": { ru: "Бензин", en: "Fuel" },
} as const;

type TranslationKey = keyof typeof translations;

export function t(key: TranslationKey, lang: Lang): string {
  return translations[key]?.[lang] || key;
}

export const LangContext = createContext<{
  lang: Lang;
  setLang: (lang: Lang) => void;
}>({
  lang: "ru",
  setLang: () => {},
});

export function useLang() {
  return useContext(LangContext);
}
